#############################################################################
# Author: Wen Li
# Date  : 1/18/2020
# Description: compilation of control module
##############################################################################
SOURCE_PATH  = source
INCLUDE_PATH = include

OBJ_PATH     = obj

CUR_CFLAGS      = $(CFLAGS) -I$(INCLUDE_PATH)
CUR_LD_CFLAGES  = $(LD_CFLAGES)

SOURCE_FILES = $(wildcard $(SOURCE_PATH)/*.cpp)
OBJ_FILES    = $(addprefix $(OBJ_PATH)/, $(addsuffix .o,$(notdir $(basename $(SOURCE_FILES)))))

TARGET = $(LIB_PATH)/libcontrol.so

.PHONY:all clean

all: $(TARGET)

$(TARGET): $(OBJ_FILES)
	$(LD) -shared -o $@ $^ $(CUR_LD_CFLAGES)
	
$(OBJ_PATH)/%.o: $(SOURCE_PATH)/%.cpp
	@if [ ! -d $(OBJ_PATH) ];then mkdir $(OBJ_PATH); fi
	$(CC) $(CUR_CFLAGS) -c -o $@ $<

clean:
	rm -rf $(OBJ_PATH) $(TARGET)
